name: Approval

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, world!"

      - name: Send approval request email for build
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'Action needed: Approve Build'
          to: manikanta@middlewaretalents.com
          from: github-actions@example.com
          body: |
            Hello Manikanta,

            Please approve the build by clicking the link below:

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Once approved, the deployment job will proceed automatically.

            Thanks!

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      deployment_url: https://github.com/${{ github.repository }}/deployments/${{ github.run_id }}
      reviewers: 
        - manikanta@middlewaretalents.com  # Existing reviewer
        - yaswanth@middlewaretalents.com  # Added new reviewer
    steps:
      - name: Wait for deployment approval
        uses: peter-evans/approve-pull-request-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            manikanta@middlewaretalents.com
            yaswanth@middlewaretalents.com
          message: "Please approve the deployment."

      - name: Deployment after approval
        run: echo "Deployment approved and running....."
