name: Approval

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, world!"

      - name: Send approval request email
        uses: dawidd6/action-send-mail@v3
        with:
          smtp-server: smtp.gmail.com  # Correct Gmail SMTP server
          smtp-port: 587  # Use 587 for TLS or 465 for SSL
          smtp-username: ${{ secrets.GMAIL_USERNAME }}  # GitHub Secret for your Gmail email
          smtp-password: ${{ secrets.GMAIL_PASSWORD }}  # GitHub Secret for your Gmail app-specific password
          from: github-actions@example.com
          to: manikanta@middlewaretalents.com
          subject: 'Action needed: Approve deployment'
          body: |
            Hello Manikanta,

            Please approve the deployment by clicking the link below and approving 
            the deployment in the 'production' environment on GitHub Actions:

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Once approved, the deployment job will proceed automatically.

            Thanks!

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deployment after approval
        run: echo "Deployment approved and running..."
